version: '3'

services:
    cia:
        build: ./packages/cia
        container_name: cia_svc
        volumes:
            - type: bind
              source: ./packages/cia
              target: /usr/src
            - type: volume
              source: cia_volume
              target: /usr/src/node_modules
        ports:
            - '3000:3000'

    ui:
        build: ./
        container_name: ui_scv
        depends_on:
          - cia
        volumes:
          - type: bind
            source: ./packages/ui
            target: /usr/src
          - type: volume
            source: ui_volume
            target: /usr/src/node_modules
        ports:
          - '9000:9000'
      
volumes:
    cia_volume:
    ui_volume:
